### ISSUE TITLE
Which Url to use

### ISSUE THREAD

**Issue by cdietrich** [eclipse-orbit/orbit-simrel#1]
Hi, do i see it correct that 

https://download.eclipse.org/oomph/simrel-orbit/2023-09

is outdated and replaced by

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-09

**Comment by merks** [comment]
@cdietrich 

I've migrated the oomph.incubator stuff into this repository and am slowly fleshing out the documentation:

https://github.com/eclipse-orbit/orbit-simrel#readme

These need a lot more details

- https://github.com/eclipse-orbit/orbit-simrel/blob/main/maven-osgi/README.md
- https://github.com/eclipse-orbit/orbit-simrel/blob/main/maven-bnd/README.md
- https://github.com/eclipse-orbit/orbit-simrel/blob/main/orbit-aggregation/README.md

So yes, you see it correctly...

Right now @jonahgraham is busy pruning the EBR-based Orbit repository.

@jonahgraham 

Other than documentation, I've pretty much got everything in place.  You mentioned changing some of the composites in downloads to refer to the new repository locations, but we probably need to touch bases sooner rather than later to flesh out the details.  

One concern I have is that the aggregation build:

https://ci.eclipse.org/orbit/job/orbit-simrel-orbit-aggregation

will build using https://download.eclipse.org/tools/orbit/downloads/latest-I by default so we can't really just redirect https://download.eclipse.org/tools/orbit/downloads/latest-I to https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/latest unless we have a new "latest" purely for Orbit EBR-based builds that we can use instead.

In any case, we need to finalize these details and make announcements on cross-projects soon.

**Comment by cdietrich** [comment]
thx, is there an issue for the pruning?
last time icu (the old one) was removed but this once might still be needed for old imports like xpand has it.

**Comment by merks** [comment]
There is this issue:

https://github.com/eclipse-orbit/orbit/issues/25

If people continue to need old things they can continue by getting them from old repositories.   We need to move forward to reduce the cost on maintenance and support...

There is currently only one version of icu on the train:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/132ade46-364b-45a0-90d9-ff7c77df9919)

That's not the one from Orbit EBR...

**Comment by merks** [comment]
I see that Xpand has a setup, but it's probably out-of-date because I think it migrated to gitlab didn't it?  What are the challenges for maintaining up-to-date dependencies and doing builds?  Where would one track such an issue?

**Comment by cdietrich** [comment]
the problem is i am not an xpand committer and xpand never made it to cbi.
so the only solution is to remove all xpand related features from xtext.
which is currently blocked by https://github.com/eclipse/Xpect/issues/320 (Xpect still uses old xtext generator)

right now i try with
e.g. https://github.com/xtext/xtext-reference-projects/blob/227cd2b31ec4cda35ed3dd6552656d0df62923ec/integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target#L61

but this is also ugly as other transitive stuff from there might bubble in

**Comment by cdietrich** [comment]
see also https://github.com/eclipse/xtext/issues/2729

**Comment by jonahgraham** [comment]
> One concern I have is that the aggregation build:

Lets make a new URL for EBR only ones then, e.g. we can just choose another letter and make https://ci.eclipse.org/orbit/job/orbit-recipes/build?delay=0sec use that by default. e.g. simrel-orbit nightly can consume from  https://download.eclipse.org/tools/orbit/downloads/latest-N

WDYT? If that works I can make the change immediately.

**Comment by merks** [comment]
Perfect, that works for me!

**Comment by jonahgraham** [comment]
The first N-build is running now - https://ci.eclipse.org/orbit/job/orbit-recipes/ - when it is done it should create the latest-N automatically. I have also updated the [webpage](https://download.eclipse.org/tools/orbit/downloads/) to show N builds instead of I builds.

Still need to update opening paragraph in the webpage - which is [stored here](https://github.com/eclipse-orbit/orbit/blob/main/releng/website/downloads/index.php) and copied to download.eclipse.org with [this job](https://ci.eclipse.org/orbit/job/orbit-sync-html-files/). I will update this once we get a full round trip done.

---

Going forward, should we stop producing S and R builds on EBR-based Orbit and use just orbit-simrel as the S and R builds?

**Comment by merks** [comment]
Yes, the milestone and release builds for the aggregation can consume from any source, so N build would sufficient.

**Comment by jonahgraham** [comment]
https://download.eclipse.org/tools/orbit/downloads/latest-N/ is now live.

**Comment by jonahgraham** [comment]
> Yes, the milestone and release builds for the aggregation can consume from any source, so N build would sufficient.

To confirm the plan - once you get all the last bits in place we are going to redirect (using composites) the following:

Immediately (once ready):

https://download.eclipse.org/tools/orbit/downloads/latest-I -> https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/latest/

In preparation for 2023-09 M2 - approximately July 25:

https://download.eclipse.org/tools/orbit/downloads/latest-S -> https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-09

Final build for 2023-09 (R-build) - approximately Sep 5:

https://download.eclipse.org/tools/orbit/downloads/latest-R -> https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-09

Then for 2023-12 M1 - approximately Sep 26:

https://download.eclipse.org/tools/orbit/downloads/latest-S -> https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-12

and so on forever?

**Comment by merks** [comment]
Yes, that sounds very good!

I'll make some refinements accordingly tomorrow.

**Comment by akurtakov** [comment]
I guess this one can be closed now, right?

**Comment by merks** [comment]
This discussion outlines which URLs to use:

https://github.com/orgs/eclipse-orbit/discussions/49
