### ISSUE TITLE
two versions of guava show up on webpage, but only one in actual repo

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-orbit/orbit-simrel#10]
On the [webpage for M3](https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/milestone/S202308151256/index.html) two versions of guava seem to appear in the following locations

- Orbit Maven OSGi All 4.29

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/679236/f22ebddb-9315-48ca-a1cf-ebc3ef8de6e3)

- Guava: Google Core Libraries for Java 32.1.2  2,970.3KB

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/679236/b5c9e022-3bea-4b7e-9189-dd1a648e2731)

The repo only contains the 32.1.2 version (as expected) but I don't understand where the first entry on the webpage comes from, the feature.xml seems to refer to 32.1.2 IIUC.

This may be a resolved problem as [latest nightly doesn't have the problem](https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/N202308151221/index.html)

**Comment by merks** [comment]
It looks a bit like a glitch in the generator.

If one looks in the actual metadata for the feature in

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/milestone/S202308151256/content.jar

one sees this:

```
    <unit id='org.eclipse.orbit.maven.osgi.all.feature.group' version='4.29.0' singleton='false'>
      <requires size='180'>
        <required namespace='org.eclipse.equinox.p2.iu' name='com.google.guava' range='[32.1.2.jre,32.1.2.jre]'/>
```

But note in particular that generated feature has no qualifier, just 4.29.0, which is why it's easily mistaken for the same feature in the previous milestone.  I tried using .qualifier in the name (in the *.target), but the Tycho build process doesn't expand to the build timestamp.

It was never intended for people to install the feature itself, so it didn't seem to be of much concern; but that the generator confuses it is rather annoying.  I'll have to think about how to work around this problem...

**Comment by merks** [comment]
A qualifier is added and will be updated whenever the content (i.e., dependencies) change. 

I am unable to build currently because of

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3562

I'll leave this issue open until I confirm the next time the content changes that the generated index contains the correct feature version with the correct dependencies.

**Comment by merks** [comment]
With the additional qualifier, the generated page for https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/milestone/latest looks up-to-date now.

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/5ec55598-b302-4008-bc19-52cf81761670)
