### ISSUE TITLE
Continue to provide lpg.runtime.java

### ISSUE THREAD

**Issue by ewillink** [eclipse-orbit/orbit-simrel#11]
Please see the queries in https://bugs.eclipse.org/bugs/show_bug.cgi?id=579583 which should have migrated.

**Comment by merks** [comment]
Looking in the details of the bundle, this appears to be the version produced by Orbit and then published to Maven by who know whom:
```
Eclipse-SourceReferences: scm:cvs:pserver:dev.eclipse.org:/cvsroot/too
 ls:org.eclipse.orbit/net.sourceforge.lpg.lpgjavaruntime;tag=v20100427
 1650
```
So I would expect and assume that no new version of this will ever be produced...

**Comment by ewillink** [comment]
I suspect it dates from the early Maven days when random users contributed their favourite libraries; there are some very old EMF / OCL / UML2 contributions. Since LPG is pretty mature maybe the old contribution will do, but is it signed correctly? (The Orbit variant is now diagnosed as unsigned by (https://download.eclipse.org/oomph/archive/simrel/ocl.aggrcon/index.html)

(A new student seems to have started running with LPG again, but evolution seems to be wrt additional supported platforms.)

If the Maven central version is ok, am I right in thinking that there is no need to resuscitate LPG-in-Orbit? I just need to learn to use a new repo source.

**Comment by merks** [comment]
It's trivial to add  it and I have already done so.  I ran this report to ensure all is fine:

https://download.eclipse.org/oomph/archive/reports-extra/orbit-aggregation-nightly/download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/latest/https___download.eclipse.org_tools_orbit_simrel_orbit-aggregation_nightly_N202308220631.html

And because the signature is no longer recognized as a strong signature, a PGP signature is generate:

https://download.eclipse.org/oomph/archive/reports-extra/orbit-aggregation-nightly/download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/latest/https___download.eclipse.org_tools_orbit_simrel_orbit-aggregation_nightly_N202308220631/lpg.runtime.java_2.0.17.v201004271640.html

I'm building the milestone repositories now and will post an update here when that is done.

**Comment by merks** [comment]
This repository now contains lpg.runtime.java:

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/milestone/latest

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/3432f24b-2af4-48a3-bb2e-9005a0030d22)

So does

https://download.eclipse.org/tools/orbit/downloads/latest-S/

**Comment by ewillink** [comment]
Thanks

> I just need to learn to use a new repo source.

or rather can just revert to the old way using Orbit's latest
