### ISSUE TITLE
Spurious net.sourceforge.lpg.lpgjavaruntime

### ISSUE THREAD

**Issue by ewillink** [eclipse-orbit/orbit-simrel#23]
While checking https://ci.eclipse.org/simrel/job/simrel.build/job/main/34/consoleFull to see whether the updated no-LPG-redistribution OCL contribution looks ok, I notice

   00:03:14  - mirroring artifact osgi.bundle,org.eclipse.datatools.sqltools.data.ui,1.5.0.202305310959
   00:03:14  - mirroring artifact osgi.bundle,net.sourceforge.lpg.lpgjavaruntime,1.1.0.v201004271650

as well as 

   00:03:27  - mirroring artifact osgi.bundle,org.eclipse.ocl.examples.xtext.idioms.ui.source,1.19.0.v20231016-0649
   00:03:27  - mirroring artifact osgi.bundle,lpg.runtime.java.source,2.0.17.v201004271640

This matches what the old Orbit offered. But AFAIAA only lpg.runtime.java is required to provide the lpg.runtime package.

I suspect this stems from a longstanding confusion. The two bundles have similar class names but lpg.runtime.java is typically 10% bigger and version 2.x rather than 1.x. Although net.sourceforge.lpg.lpgjavaruntime is a superficially better name properly reflecting its domain authorities and was built 10 minutes later, it is version 1 rather than version 2.

I suggest that net.sourceforge.lpg.lpgjavaruntime need not be provided by the new stripped down Orbit. (I'm not sure whether the log line sequencing indicates that the datatools distribution needs updating.)

(My 4.30M1 installation uses just lpg.runtime.java for OCL and friends.)

**Comment by merks** [comment]
The aggregation contains exactly what OCL includes which is exactly the version that comes from Orbit's aggregation:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/c3ae38b6-0e6f-4a37-9afb-129c3bc25475)

What exactly are you asking me to change in Orbit?  You're asking me not to provide (delete) the exact bundle that your contributed feature exactly requires?  I.e., you're asking me to just remove the following because you don't need it and will instead get something else (better?) from somewhere else instead?

https://github.com/eclipse-orbit/orbit-simrel/blob/f28edfc263125981ba7a782a661f00ba7e80b2c8/maven-osgi/tp/other/MavenSupplement.target#L246-L251

Oh wait, maybe you are suggesting that datatools is bad because it uses this other bundle by name:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/7ac7f73c-31d7-4449-9802-9a2ea9cc33e8)

In that case, it's not an Orbit problem at all but rather a data tools problem that needs to be fixed here, probably by using a package import and not a bundle import:

https://github.com/eclipse-datatools/datatools

Is that your point?

**Comment by ewillink** [comment]
Yes, it is a datatools problem for consuming an unnecessarily obsolete bundle.

It is also a new-Orbit problem for providing net.sourceforge.lpg.lpgjavaruntime.

You kindly organised the provision of the latest version lpg.runtime.java in new-Orbit; thank you.

I'm suggesting that you did not need to do the same for net.sourceforge.lpg.lpgjavaruntime, and were perhaps decieived by the distinct bundle names into thinking that they were different products.

IMHO datatools should either upgrade or redistribute from old Orbit. New-Orbit should not provide net.sourceforge.lpg.lpgjavaruntime.

**Comment by merks** [comment]
Orbit does not provide that bundle:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/25c88c69-8674-4682-b41c-71a7e6010eba)

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/c3d13e9f-7aa9-4286-92aa-9fb7f72d726e)

But indeed, DataTools ought to only use the latest Orbit things.  I thought I was smart not to include anything in contributed features for DataTools, but it's not enough because of course if there are dependencies on the bundle name, then old stuff can still be dragged in, and that's exactly what's happens. 

Thanks for drawing my attention to that!  👍

**Comment by merks** [comment]
FYI, unfortunately the packages exported by that bundle are different and DataTools exports the imported bundle to make matters worse.

**Comment by ewillink** [comment]
FYI:

IMP https://bugs.eclipse.org/bugs/show_bug.cgi?id=298542 discusses the inconsistent lpg.runtime.java bundle id.

OCL https://bugs.eclipse.org/bugs/show_bug.cgi?id=242153 discusses at very great length the need for OCL to migrate to LPG 2 so that the IMP editor generators could be used. It also mentions migration difficulties and getting LPG2 into Orbit.

As it transpired, IMP had an IP issue that prevented IMP-based editors being released. Fortunately Xtext appeared with perfect timing so that Xtext-based editors were provided instead.
