### ISSUE TITLE
Tag commits used for Orbit releases

### ISSUE THREAD

**Issue by pcdavid** [eclipse-orbit/orbit-simrel#32]
It's not obvious (to me) which commit in this repo corresponds to what was released as https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-12/index.html

I can try to infer based on dates, but having actual tags would be much easier.

My actual use case is to be able to see "what has changed in Orbit since the last release that might concern me?". I can look at https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-12/index.html and https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2024-03/index.html but the "diff" is not obvious.

I'd like to be able to do something like `git log v2023-12..` (or `diff`) on my local clone and see what changed (with commit messages for context).

**Comment by merks** [comment]
I'm a little doubtful that pawing through commit history is a good solution to the actual problem.   Content is also aggregated from https://github.com/eclipse-orbit/orbit-legacy which of course has its own commit history.   In any case, it's easy to search commits since the date of the release without tags:

https://github.com/eclipse-orbit/orbit-simrel/commits/main/?since=2023-12-05

Perhaps some type of generated table/report would be more useful.  E.g., one could have the rows be the bundles and the columns be the releases (including the current ongoing one), then each cell could be the version of that bundle in that release.  But I don't want to do a bunch of work that almost no one will actually look at...

**Comment by merks** [comment]
The [org.eclipse.justj.p2.manager](http://localhost/justj/?page=tools) now supports generating a tabular summary:

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/table.html

The table includes markup to show versions that have changed:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/e30cda31-6e9f-47db-bc7c-a4c8e32d6c02)
